version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - echo Installing dotnet SDK
  pre_build:
    commands:
      - echo Restoring NuGet packages
      - dotnet restore
  build:
    commands:
      - echo Building .NET application
      - dotnet build -c Release
  post_build:
    commands:
      - echo Publishing application artifacts
      - dotnet publish -c Release -o ./artifacts

artifacts:
  files:
    - ./artifacts/**
